In [1]:
'''
【课程1.2】 Numpy基础数据结构

Numpy数组是一个多维数组对象，成为ndarray。其由两部分组成：
① 实际的数据
② 描述这些数据的元数据
'''

'\n【课程1.2】 Numpy基础数据结构\n\nNumpy数组是一个多维数组对象，成为ndarray。其由两部分组成：\n① 实际的数据\n② 描述这些数据的元数据\n'

In [5]:
# 多维数组ndarray
import numpy as np

ar = np.array([[1,2,3,4,5,6],[5,6,7,8,9,10],[5,6,7,8,9,10]]) #list长度要一直
print([1,2,3,4,5,6])
print(ar,type(ar))
# 疑问：np.array与np.ndarray区别在哪里，为什么上述用np.ndarray会报错

print(ar.ndim) #返回数组的维数
print(ar.shape) # 返回数组的组成结构
print(ar.size) # 返回数组的长度
print(ar.dtype) # 返回数的值的类型,于type有什么区别，type返回结构类型
print(type(ar))
print(ar.itemsize)# array 元素的字节数
print(ar.data)

[1, 2, 3, 4, 5, 6]
[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]
 [ 5  6  7  8  9 10]] <class 'numpy.ndarray'>
2
(3, 6)
18
int32
<class 'numpy.ndarray'>
4


In [9]:
# 创建数组：array()函数，括号内可以是列表、元组、数组、生成器等

ar1 = np.array(range(10))
print(ar1)
ar2 = np.arange(10)  #与range有何区别
print(ar2)
ar3 = np.array([1,2,3,4,5])
print(ar3,ar3.dtype)
ar4 = np.array([[1,2,3,4],['a','b','c','d']])
print(ar4,ar4.dtype,ar4.ndim)
print(np.random.rand(10).reshape(2,5))


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5] int32
[['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']] <U11 2
[[0.05101902 0.38706845 0.48833005 0.9057953  0.64046692]
 [0.26528937 0.59446687 0.80101188 0.57766472 0.58678064]]


In [17]:
# 创建数组：array()函数，括号内可以是列表、元组、数组、生成器等
ar1 = np.array(range(10)) #整型
ar2 = np.array([1,2,3.14,4,5]) #浮点型
ar3 = np.array([[1,2,3],('a','b','c')]) #二维数组：嵌套序列（列表，元组均可）
ar4 = np.array([[1,2,3],('a','b','c','d')]) #嵌套序列数量不一会怎样？

print(ar1,type(ar1),ar1.dtype)
print(ar2,type(ar2),ar2.dtype)
print(ar3,ar3.shape,ar3.ndim,ar3.size)
print(ar4,ar4.shape,ar4.ndim,ar4.size)
print(ar3.itemsize)# ar3 与 ar4的差距在哪？
print(ar4.itemsize)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32
[1.   2.   3.14 4.   5.  ] <class 'numpy.ndarray'> float64
[['1' '2' '3']
 ['a' 'b' 'c']] (2, 3) 2 6
[list([1, 2, 3]) ('a', 'b', 'c', 'd')] (2,) 1 2
44
8


In [18]:
# 创建数组：arange(), 类似range()，在给定间隔内返回均匀间隔的值。
print(np.arange(10)) # 返回0-9，整型
print(np.arange(10.0)) # 返回0.0-9.0 浮点型
print(np.arange(5,12)) # 返回5-11
print(np.arange(5.0,12,2)) # 返回5.0-12.0，步长为2
print(np.arange(10000)) #数值太多，自动跳过中间，只打印边角

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11]
[ 5.  7.  9. 11.]
[   0    1    2 ... 9997 9998 9999]


In [22]:
# 创建数组：linspace(): 返回在间隔[开始，停止]上计算的num个均匀间隔的样本
ar1 = np.linspace(2.0,3.0,num=5)
ar2 = np.linspace(2.0,3.0,num=5, endpoint=False)
ar3 = np.linspace(2.0,3.0,num=5, retstep=True)
print(ar1,type(ar1))
print(ar2)
print(ar3,type(ar3))
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# start：起始值，stop：结束值
# num：生成样本数，默认为50
# endpoint：如果为真，则停止是最后一个样本。否则，不包括在内。默认值为True。
# retstep：如果为真，返回（样本，步骤），其中步长是样本之间的间距 → 输出为一个包含2个元素的元祖，第一个元素为array，第二个为步长实际值

[2.   2.25 2.5  2.75 3.  ] <class 'numpy.ndarray'>
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) <class 'tuple'>


In [23]:
# 创建数组：zeros()/zeros_like()/ones()/ones_like()
ar1 = np.zeros(5)
ar2 = np.zeros((2,2), dtype=np.int)
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)
print('--'*20)
# numpy.zeros(shape, dtype=float, order='C'):返回给定形状和类型的新数组，用零填充。
# shape：数组纬度，二维以上需要用()，且输入参数为整数
# dtype：数据类型，默认numpy.float64
# order：是否在存储器中以C或Fortran连续（按行或列方式）存储多维数据。

ar3 = np.array([list(range(5)),list(range(5,10))])
ar4 = np.zeros_like(ar3)
print(ar3)
print(ar4)
print('---'*20)
# 返回具有与给定数组相同的形状和类型的零数组，这里ar4根据ar3的形状和dtype创建一个全0的数组

ar5 = np.ones(9)
ar6 = np.ones((2,3,4))
ar7 = np.ones_like(ar3)
print(ar5)
print(ar6)
print(ar7)

[0. 0. 0. 0. 0.] float64
[[0 0]
 [0 0]] int32
----------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
# 创建数组：eye（）
print(np.eye(5))
# 创建一个正方的N*N的单位矩阵，对角线值为1，其余为0

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


ndarray的数据类型

bool	用一个字节存储的布尔类型（True或False）

inti	由所在平台决定其大小的整数（一般为int32或int64）

int8	一个字节大小，-128 至 127

int16	整数，-32768 至 32767

int32	整数，-2 ** 31 至 2 ** 32 -1

int64	整数，-2 ** 63 至 2 ** 63 - 1

uint8	无符号整数，0 至 255

uint16	无符号整数，0 至 65535

uint32	无符号整数，0 至 2 ** 32 - 1

uint64	无符号整数，0 至 2 ** 64 - 1

float16	半精度浮点数：16位，正负号1位，指数5位，精度10位

float32	单精度浮点数：32位，正负号1位，指数8位，精度23位

float64或float	双精度浮点数：64位，正负号1位，指数11位，精度52位

complex64	复数，分别用两个32位浮点数表示实部和虚部

complex128或complex	复数，分别用两个64位浮点数表示实部和虚部