In [6]:
# 【课程1.2】  Numpy基础数据结构 作业
# 作业1：分别按照要求，生成一个一维数组、二维数组，并且查看其shape
import numpy as np

a1 = np.array([1,2,'a','hello',[1,2,3],{'two':200, 'one':100}])
print(a1,a1.shape)
a2 = np.array([list(range(6)),
              list('abcdef'),
              ['True','False','True','False','True','True']])
print(a2,a2.shape)

[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'one': 100}] (6,)
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'True']] (3, 6)


In [9]:
# 作业2：生成一个一维数组，起始值为5，终点为15，样本数为10个
a3 = np.array(list(range(5,16)))
print(a3)
a3 = np.arange(5,16)
print(a3)

[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [14]:
# 作业3： 按照要求创建3个数组
a1 = np.zeros((4,4))
print(a1)
a2 = np.ones((2,3))
a3 = np.eye(3)
print(a2)
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
'''
【课程1.3 Numpy 通用函数】
'''

'\n【课程1.3 Numpy 通用函数】\n'

In [8]:
# 作业1：创建一个20个元素的数组，分别改成两个形状：（4，5），（5，6）（提示：超出范围用resize）
import numpy as np
lst1 = np.arange(20).reshape((4,5))
print(lst1)
lst2 = np.resize(lst1,(5,6))
print(lst2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [11]:
# 作业2：创建一个(4,4)的数组，把其元素类型改为字符型。
ar2 = np.arange(16).reshape(4,4)
print(ar2.astype(np.str))

[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [16]:
# 作业3：根据要求创建数组，运用数组的运算方法得到结果：result = ar * 10 + 100，并求出result的均值及求和。
# 创建数组为：
ar1 = np.arange(16).reshape(4,4)
result = ar1 * 10 + 100
print(result)
print(result.mean())
print(result.sum())

[[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]]
175.0
2800


In [17]:
'''
【课程1.4  Numpy索引及切片】 课程作业

'''

'\n【课程1.4  Numpy索引及切片】 课程作业\n\n'

In [20]:
# 作业1：按照要求创建数组，通过索引，其ar[4]、ar[:2,3:]、ar[3][2]分别是多少
ar = np.arange(25).reshape(5,5)
print(ar)
print(ar[4])
print(ar[:2,3:])
print(ar[3,2])
print(ar[3][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]
[[3 4]
 [8 9]]
17
17


In [24]:
# 作业2：按照要求创建数组，筛选出元素值大于5的值并生成新的数组
ar2 = np.arange(10).reshape(2,5)
print(ar2)
print('**'*20)
print(ar2[ar2>5])

[[0 1 2 3 4]
 [5 6 7 8 9]]
****************************************
[6 7 8 9]


In [25]:
'''
【1.5】 Numpy 索引及切片，课程作业
'''

'\n【1.5】 Numpy 索引及切片，课程作业\n'

In [39]:
# 作业1：请按照要求创建数组ar，再将ar[:2,:2]的值改为[0,1)的随机数
#import random
ar2 = np.arange(25,dtype=np.float32).reshape(5,5)
print(ar2)
ar2[:2,:2] = np.random.rand(2,1) #?
print(ar2)
ar2[:2,:2] = np.random.rand(2,2) #?
print(ar2)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
[[ 0.22895584  0.22895584  2.          3.          4.        ]
 [ 0.76084405  0.76084405  7.          8.          9.        ]
 [10.         11.         12.         13.         14.        ]
 [15.         16.         17.         18.         19.        ]
 [20.         21.         22.         23.         24.        ]]
[[ 0.5796565   0.10639944  2.          3.          4.        ]
 [ 0.57994765  0.36962357  7.          8.          9.        ]
 [10.         11.         12.         13.         14.        ]
 [15.         16.         17.         18.         19.        ]
 [20.         21.         22.         23.         24.        ]]


In [47]:
# 作业2：创建2个包含10个元素的正太分布一维数组
ar1 = np.random.normal(size=(2,5))
print(ar1)
ar2 = np.random.normal(size=(2,5))
print('----\n',ar2)
print('**'*30)
print(np.stack((ar1,ar2),axis=1))

[[ 2.28155366  0.41239324 -0.45727655 -1.35563454  0.35068327]
 [ 0.51349297 -1.03779888 -0.22182156  0.32768768 -0.59925095]]
----
 [[ 0.7860292   1.51612324  0.92147581  0.10001658 -1.42317992]
 [ 1.56263164  0.97596984 -1.81543456 -0.61757833 -0.06993843]]
************************************************************
[[[ 2.28155366  0.41239324 -0.45727655 -1.35563454  0.35068327]
  [ 0.7860292   1.51612324  0.92147581  0.10001658 -1.42317992]]

 [[ 0.51349297 -1.03779888 -0.22182156  0.32768768 -0.59925095]
  [ 1.56263164  0.97596984 -1.81543456 -0.61757833 -0.06993843]]]


In [48]:
'''
【1.6】Numpy数据的输入输出 课程作业
'''

'\n【1.6】Numpy数据的输入输出 课程作业\n'

In [49]:
#作业1：创建一个10*10的整数随机数组，取值范围为0-100，并存为txt文件，用逗号分开
lst = np.random.randint(100,size=(10,10))
print(lst)
f = open(r'D:\python_note\DataPractice\02.重点工具掌握：数据解析核心技巧\array.txt','w')

[[38 29 76 39 92 88 77 32  4  0]
 [24 49 60 89 22 16 71 23 39  9]
 [45 56 38 56 84  8 92 43 80 49]
 [58 17  1 43  2 78 94 64 67 17]
 [66 37 34 63 45 36 51 57 31 30]
 [89 74 35  0 82 75 34 20 86 87]
 [ 9 86 76 35 13 65 50 12 76 18]
 [36 65 94 67 15 97 30 97 33 53]
 [ 0 54 11 48 70 46 93 65 71 80]
 [31 72 54 40 82 46 71 90 82 48]]
